version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mock-generator:
    build:
      context: ./mock_data
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # command: ["python", "generator.py"]  # padrão já é esse, pode deixar de fora
