version: "3.9"

services:
  spark-metrica:
    build: ./metrica_teste
    volumes:
      - ./artifacts:/app/artifacts




  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mock-generator:
    build:
      context: ./mock_data
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  tratador-limpeza:
    build:
      context: ./tratador_limpeza
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  tratador-filtragem:
    build:
      context: ./tratador_filtragem
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  tratador-metrica:
    build:
      context: ./tratador_metrica
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
