version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - kafka_net

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - kafka_net

  mock-generator:
    build:
      context: ./mock_data
    command: ["sh", "-c", "sleep 5 && python generator.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVERS}
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    # volumes:
    #   - resultados:/app/databases_mock
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - kafka_net

  tratador1_limpeza:
    build:
      context: ./tratadores
    command: t1_limpeza.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_net

  tratador2_filtragem:
    build:
      context: ./tratadores
    command: t2_filtrador.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_net

  tratador4_agrupar_data:
    build:
      context: ./tratadores
    command: t4_agrupar_data.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_net

  api:
    build:
      context: ./api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - tratador4_agrupar_data
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
    # volumes:
    #   - resultados:/app/databases_mock
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - kafka_net

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "${DASHBOARD_PORT}:8501"
    depends_on:
      - api
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - kafka_net

networks:
  kafka_net: