version: "3.8"

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  publisher:
    build: .
    container_name: publisher
    command: python3 mock/mock_generator.py
    depends_on:
      - redis

  spark-consumer:
    build: .
    container_name: spark-consumer
    command: spark-submit consumer/consumer_pubsub.py
    depends_on:
      - redis
