services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mock-generator:
    build:
      context: ./mock_data
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  spark-consumer:
    build:
      context: ./consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
